class Config:
    MONGO_USERNAME = ""
    MONGO_PASSWORD = ""
    MONGO_HOST = "localhost"
    MONGO_PORT = 27017
    FCM_CREDENTIALS="" 
    FCM_AUTHORIZATION_KEY=""
    MY_FCM_KEY=""
    FCM_PROJECT_ID=""
    NEWS_API_KEY="d5ed720832774c4b87a7bbd537d9ea21"